// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxlW216fM7eQq-q8-c_n01Hjol0lbJTMo',
    appId: '1:764991072860:web:f801329c59a15bfba79499',
    messagingSenderId: '764991072860',
    projectId: 'show-4abcd',
    authDomain: 'show-4abcd.firebaseapp.com',
    storageBucket: 'show-4abcd.appspot.com',
    measurementId: 'G-Z96DHWXK86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXKIkC6sL0OxAlFbxS6T4n6TAaS_ITwDQ',
    appId: '1:764991072860:android:da97e14d8086675ba79499',
    messagingSenderId: '764991072860',
    projectId: 'show-4abcd',
    storageBucket: 'show-4abcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPu3OtDtvcm1jj7IrWc06bArmESgsiUc',
    appId: '1:764991072860:ios:f0cd5a2c63d5faf0a79499',
    messagingSenderId: '764991072860',
    projectId: 'show-4abcd',
    storageBucket: 'show-4abcd.appspot.com',
    iosBundleId: 'com.example.showFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPu3OtDtvcm1jj7IrWc06bArmESgsiUc',
    appId: '1:764991072860:ios:877395772cd3930fa79499',
    messagingSenderId: '764991072860',
    projectId: 'show-4abcd',
    storageBucket: 'show-4abcd.appspot.com',
    iosBundleId: 'com.example.showFlutter.RunnerTests',
  );
}
